language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: p.dupavillon@gmail.com
  api_key:
    secure: oxkkFKnO9VLAte7QfgDW62T9+26ATDqwx2OR54/kkhKDWCx9xP1aczon+Sv+jqChKa05JFgd5NnA9xtAhfmvC6V+Nn0afMz3DxmdwMKDoCPWU9+wfgymcFxh5kJBIXJ1sWLE4GC5bRynpTKBD5csJS1w4ZBBndRdU4YVEKu7FaI=
